# Generated by Django 5.0 on 2024-11-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_posts_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='like',
            field=models.IntegerField(default=0, verbose_name='like'),
        ),
    ]
