# Generated by Django 5.0 on 2024-11-25 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_followers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Followers',
        ),
    ]
